import React from 'react';
import { QUESTIONS } from '../constants';
import { Language } from '../types';
import { Activity, Calendar, FileText } from 'lucide-react';

interface Props {
  dataString: string;
}

const REPORT_TEXTS = {
  title: { en: 'Kauvery Nalam', ta: 'காவேரி நலம்' },
  subtitle: { en: 'Official Medical Report', ta: 'அதிகாரப்பூர்வ மருத்துவ அறிக்கை' },
  refId: { en: 'Reference ID', ta: 'குறிப்பு எண்' },
  date: { en: 'Date', ta: 'தேதி' },
  responses: { en: 'Clinical Responses', ta: 'மருத்துவ பதில்கள்' },
  disclaimer: { 
    en: 'This report is automatically generated by Kauvery Nalam Digital Assessment. It does not replace a doctor\'s formal diagnosis.',
    ta: 'இந்த அறிக்கை காவேரி நலம் டிஜிட்டல் மதிப்பீட்டால் தானாக உருவாக்கப்பட்டது. இது மருத்துவரின் முறையான நோயறிதலுக்கு மாற்றாகாது.'
  },
  invalid: { en: 'Invalid Report Data', ta: 'தவறான அறிக்கை தரவு' },
  zones: {
    RED: { en: 'Action Required', ta: 'கவனம் தேவை' },
    AMBER: { en: 'Moderate Risk', ta: 'மிதமான ஆபத்து' },
    GREEN: { en: 'Healthy', ta: 'ஆரோக்கியமான நிலை' }
  }
};

export const ReportView: React.FC<Props> = ({ dataString }) => {
  let reportData;
  let answersArray: (string | null)[] = [];
  let id = '', date = '', zone = '', lang: Language = 'en';

  // Helper: Unicode-safe Base64 Decode
  const unicodeSafeAtob = (str: string) => {
    try {
      return decodeURIComponent(atob(str).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
      }).join(''));
    } catch (e) {
      console.warn("Legacy decode fallback used");
      return atob(str); // Fallback for old reports
    }
  };

  try {
    // 1. Decode Safe Base64
    const jsonString = unicodeSafeAtob(dataString);
    reportData = JSON.parse(jsonString);
    
    // Handle Compressed Payload (v1)
    if (reportData.v === 1) {
       id = reportData.i;
       date = reportData.d;
       zone = reportData.z;
       lang = reportData.l || 'en';
       answersArray = reportData.a || [];
    } else {
       // Legacy Fallback (Object based)
       id = reportData.id;
       date = reportData.date;
       zone = reportData.z;
       lang = reportData.l || 'en';
       // Convert object to array for display logic
       const answersObj = reportData.a;
       answersArray = QUESTIONS.map(q => answersObj[q.id] || null);
    }

  } catch (e) {
    console.error("Report Parse Error", e);
    return <div className="p-10 text-center text-red-500 font-bold">Invalid Report Data</div>;
  }

  // Helper to safely get zone text
  const getZoneText = (z: string) => {
    if (z === 'RED') return REPORT_TEXTS.zones.RED[lang];
    if (z === 'AMBER') return REPORT_TEXTS.zones.AMBER[lang];
    return REPORT_TEXTS.zones.GREEN[lang];
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-safe">
      {/* Report Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
             <div className="w-10 h-10 bg-kauvery-primary rounded-xl flex items-center justify-center text-white">
               <Activity size={20} />
             </div>
             <div>
               <h1 className="text-sm font-extrabold uppercase text-gray-900 leading-none mb-1">
                 {REPORT_TEXTS.title[lang]}
               </h1>
               <p className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">
                 {REPORT_TEXTS.subtitle[lang]}
               </p>
             </div>
          </div>
          <div className={`px-3 py-1 rounded-full text-xs font-bold border ${
            zone === 'RED' ? 'bg-red-50 text-red-700 border-red-100' :
            zone === 'AMBER' ? 'bg-orange-50 text-orange-700 border-orange-100' :
            'bg-green-50 text-green-700 border-green-100'
          }`}>
            {getZoneText(zone)}
          </div>
        </div>
      </div>

      <div className="max-w-xl mx-auto px-6 py-8">
        {/* Patient Info Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-8">
           <div className="grid grid-cols-2 gap-6">
              <div>
                <p className="text-[10px] uppercase font-bold text-gray-400 mb-1 flex items-center gap-1">
                  <FileText size={10} /> {REPORT_TEXTS.refId[lang]}
                </p>
                <p className="font-mono text-sm font-bold text-gray-900">{id}</p>
              </div>
              <div className="text-right">
                <p className="text-[10px] uppercase font-bold text-gray-400 mb-1 flex items-center justify-end gap-1">
                  <Calendar size={10} /> {REPORT_TEXTS.date[lang]}
                </p>
                <p className="font-mono text-sm font-bold text-gray-900">
                  {new Date(date).toLocaleDateString()}
                </p>
              </div>
           </div>
        </div>

        {/* Detailed Q&A List */}
        <h3 className="text-sm font-bold text-gray-900 uppercase tracking-widest mb-4 pl-1">
          {REPORT_TEXTS.responses[lang]}
        </h3>
        <div className="space-y-4">
          {QUESTIONS.map((q, index) => {
             // Get answer from array based on index
             const answer = answersArray[index];
             
             if (!answer) return null; // Skip questions not answered
             
             // Find full label of answer for display
             const optionLabel = q.options.find(opt => opt.val === answer)?.label[lang] || answer;

             return (
               <div key={q.id} className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
                 <div className="flex gap-3">
                    <span className="text-xs font-bold text-gray-300 w-5 pt-0.5">{index + 1}.</span>
                    <div>
                      <p className="text-sm font-semibold text-gray-800 mb-2 leading-snug">
                        {q.label[lang]}
                      </p>
                      <div className="inline-block bg-gray-50 px-3 py-1.5 rounded-lg border border-gray-100">
                         <p className="text-sm font-bold text-kauvery-primary">
                           {optionLabel}
                         </p>
                      </div>
                    </div>
                 </div>
               </div>
             );
          })}
        </div>
        
        <div className="mt-12 text-center">
          <p className="text-[10px] text-gray-400 font-medium max-w-xs mx-auto leading-relaxed">
            {REPORT_TEXTS.disclaimer[lang]}
          </p>
        </div>
      </div>
    </div>
  );
};